Rotating proxies
AyeshaSiddique01/webscrapy_training pull request #8
Opened 2024-04-17 11:41 UTC by AyeshaSiddique01

2024-04-17 12:18 UTC, faisal05sa requested changes

2024-04-17 12:18 UTC, faisal05sa commented on clothing_app/clothing_app/middlewares.py
> +            Proxy("http://stylesage:O5s6a9jaAs@66.56.67.157:60000"),
We should not write proxies OR any credentials/configurations in the code. It should be in separate files. So, create a file `proxies.txt` in some folder and add its path in the settings file. Use that path in the middleware to read the file and load the proxies.

2024-04-17 12:18 UTC, faisal05sa commented on clothing_app/clothing_app/middlewares.py
> +            selected_weight = self.proxy_manager.weighted_random_selection()
`weighted_random_selection` should return a proxy. The weights are the internal mechanism of the proxy_manager. In the future, we can implement another ProxyManager with another algorithm that does not need weights.

2024-04-17 12:18 UTC, faisal05sa commented on clothing_app/clothing_app/middlewares.py
> +            self.proxy = self.proxies[selected_weight]
Scrapy is an asynchronous framework. It can send many requests at a time. `self.proxy` will only store the proxy of the last processed request.

2024-04-17 12:18 UTC, faisal05sa commented on clothing_app/clothing_app/middlewares.py
> +            self.proxy.select_proxy("blocked")
```python
used_proxy = get_used_proxy_for_request(request)
self.proxy_manager.reduce_weight(used_proxy)
```
OR If you have implemented the observer pattern
```python
used_proxy = get_used_proxy_for_request(request)
used_proxy.reduce_weight()
```
similarly,
```python
used_proxy.increase_weight()
```

2024-04-17 12:18 UTC, faisal05sa commented on clothing_app/clothing_app/select_proxy.py
> +import random
Inherit the code that has already been merged. OR wait for the merging of other PRs before changing this file.

2024-04-18 08:05 UTC, AyeshaSiddique01 commented on clothing_app/clothing_app/middlewares.py
> +            self.proxy.select_proxy("blocked")
I have called `update_weight()` in ProxyManager(observable class) which reduces or increases proxy weight according to their status. Should I have `reduce_weight()` and `increase_weight()` in observer class?

2024-04-18 09:04 UTC, AyeshaSiddique01 commented on clothing_app/clothing_app/select_proxy.py
> +import random
yes, I'm waiting for observer_weighted_random_Selection PR to merge.

2024-04-26 08:29 UTC, faisal05sa requested changes

2024-04-26 08:29 UTC, faisal05sa commented on clothing_app/clothing_app/middlewares.py
> +class ClothingAppProxyMiddleware(object):
Name this class as "RotateProxyMiddleware". It is only responsible for choosing a suitable proxy from a list. It maintains some weights and randomly selects that proxy.
It just sets `request['meta']['proxy'] = 'http:user:pass@ip:port'. Builtin proxy middleware will take care of settings auth headers etc.

2024-04-26 08:29 UTC, faisal05sa commented on clothing_app/clothing_app/select_proxy.py
> +    MAX_WEIGHT = 100
`MAX_WEIGHT = 100` should be defined in the parent class. Obviously, we can override it here if needed.

2024-04-26 10:41 UTC, faisal05sa approved these changes
👍🏼

2024-04-26 10:42 UTC, merged